// LOCALHOST
### Get all drugs
GET http://localhost:5000/drugs

### Get drugs by id
GET http://localhost:5000/drugs/674e9593f05fdd70065f4fb4

### Get drugs by commercial name
GET http://localhost:5000/drugs/cn/tylenol

### Get drugs by scientific name
GET http://localhost:5000/drugs/sn/montelukast

### Get drugs by category
GET http://localhost:5000/drugs/category/painkiller

### Create a drug
POST http://localhost:5000/drugs HTTP/1.1
content-type: application/json

{
"scientificName": "testing-scientific",
"VendorId": "674eccc0118c49fc41d19032",
"expireDate": "2024-09-10",
"doses": "testing",
"description": "we are testing",
"commercialName": "testing"
}


### Update a drug
PUT http://localhost:5000/drugs/674ee7d4c70aaca2e583e34c HTTP/1.1
content-type: application/json

{
    "scientificName": "testing-purpose-updating-test",
    "VendorId": "674eccc0118c49fc41d19032",
    "expireDate": "testing",
    "doses": "testing",
    "description": "we are testing",
    "commercialName": "testing"
}
### DELETE a drug
DELETE http://localhost:5000/drugs/67509e3e1672a388f3635f1c HTTP/1.1


###Get Vendors
GET http://localhost:5000/vendors

###Create a new vendor
POST http://localhost:5000/vendors HTTP/1.1
Content-Type: application/json

{
    "name": "test",
    "phone": "862-404-3000",
    "address": "100 Bayer Boulevard Whippany, NJ 07981",
    "rating": 5,
    "itin": "123-45-6223"
}

###Get by name
GET http://localhost:5000/vendors/findbyname/bayer

###Get by itin
GET http://localhost:5000/vendors/findbyitin/123-45-6789

###Update Vendor
PUT http://localhost:5000/vendors/6750892ef2c4184e3f4059be HTTP/1.1
Content-Type: application/json

{
    "name": "new test",
    "phone": "862-555-4026"
}

###Delete vendor
DELETE http://localhost:5000/vendors/6750892ef2c4184e3f4059be HTTP/1.1
